### ISSUE TITLE
点击音频播放不了，循环那1秒之间的音频

### ISSUE THREAD

**Issue by webthen** [wangduanduan/element-audio#1]
版本 ：element 1.4
点击播放的时候，卡在1s的音频里循环播放。
注释掉changeCurrentTime 里面的代码不会，parseInt 换成Math.ceil 可以，但是把this.$refs.audio.currentTime 值增加了
方法：
changeCurrentTime 和 onTimeupdate 有出入。

麻烦看下

**Comment by wangduanduan** [comment]
我把音频文件换了一个较长的，星球坠落，https://wdd.js.org/element-audio/
